server:
  port: 8080
jwt:
  secret: $2a$12$kZFc6e2lo/x8/HegxuBNyeI6hsSXWXytYd.hCvlmvbqdoX5PnCL22
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    username: patrondev
#    password: patrondev201703!
#    url: jdbc:mariadb://20.249.79.13/patron_dev?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: nodamen@mariadb-patron-kt
    password: mariadbpatron1703!
    url: jdbc:mariadb://mariadb-patron-kt.mariadb.database.azure.com/kt_streaming?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      max-lifetime: 30000
      connection-timeout: 33000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true

    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: true
#    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 860400

#logging:
#  file:
#    name: logs/Logs.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

