# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# 파이프라인 트리거 main branch
trigger:
- main

resources:
- repo: self

# job 단계에 사용할 변수 선언
variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6410b9c6-1418-4108-8023-29d8b9d85579'
  imageRepository: 'nodamenpipelinesjavadocker'
  containerRegistry: 'acrdev0327.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

# CI Stage
stages: # 작업 단계 의미 Build 혹은 Deploy 로 나누어진다.
- stage: Build
  displayName: Build and push stage
  jobs: # stages 안에서 작업할 job 들 하나의 task를 의미한다.
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps: # job의 세부 단계
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
