# syntax=docker/dockerfile:1

# 도커 허브에서 제공하는 nginx alpine 이미지 가져오기
FROM nginx:1.23-alpine

# 개발자가 작성한 nginx.conf 파일을 기존 nginx 구성 파일 경로로 복사한다
COPY nginx.conf /etc/nginx/nginx.conf
# 개발자가 작성한 index.html 파일을 기존 nginx 루트 파일 경로로 복사한다
COPY index.html /usr/share/nginx/html
# 개발자가 생성한 log 파일을 기존 nginx 로그 파일 경로로 복사한다
COPY log /var/log/nginx

EXPOSE 80