# docker-compose.yml

version: "3.9"
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: acrprod0327.azurecr.io/production/spring-app
    container_name: spring-app
    ports:
      - "8080:8080"
    networks:
      - patron
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: acrprod0327.azurecr.io/production/nginx-alpine
    container_name: nginx-alpine
    ports:
      - "80:80"
    networks:
      - patron
    links:
      - spring-app
    depends_on:
      - spring-app
networks:
  patron: