# docker-compose.yml

version: "3.9"
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: spring-app
    container_name: springApp
    ports:
      - "80:8080"
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx-alpine
    container_name: nginxAlpine
    ports:
      - "80:80"
    depends_on:
      - spring-app

    # volumes:
    #   - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - /var/log/nginx:/var/log/nginx