jwt:
  header: generalMemberization
  secret: $2a$12$kZFc6e2lo/x8/HegxuBNyeI6hsSXWXytYd.hCvlmvbqdoX5PnCL22
  access: 600000
  refresh: 1800000


---
spring:
  profiles:
    group:
      "dev": "testDB,common"

---
spring:
  profiles:
    active: dev

server:
  port: 8080
---
spring:
#  messages:
#    escape-html: false
  cache:
    jcache:
      config: ehcache.xml
  config:
    activate:
      on-profile: "testDB"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    username: patrondev
#    password: patrondev201703!
#    url: jdbc:mariadb://20.249.79.13/patron_dev?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: nodamen@mariadb-patron-kt
    password: mariadbpatron1703!
    url: jdbc:mariadb://mariadb-patron-kt.mariadb.database.azure.com/kt_streaming?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      max-lifetime: 20000
      connection-timeout: 33000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    #        format_sql: true

    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nodamen17@gmail.com
    password: mjsshjmjppktdcjt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 231274344020-94njuov1dotof3jh82rqemq7a2hn7cbg.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 650158759616850
            client-secret: f2da757fe103b3082996777bfe89c014
#logging:
#  file:
#    name: logs/Logs.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

server:
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto

  servlet:
    session:
      timeout: 24h
#TODO 배포전 체크사항
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: nodamen
#    key-store-type: PKCS12
#    key-alias: bns-ssl
#  port: 8081

#cors:
#  allowed-origins: 'http://localhost:8080 , https://211.217.233.62:8080'
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#  allowed-headers: '*'
#  max-age: 3600

bucket4j:
  filters[0]:
    rate-limits[0]:
      bandwidths[0]:
        time: 1
        capacity: 10000
        unit: minutes
    http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
    strategy: first
    url: .*
    cache-name: buckets
    filter-method: servlet
  enabled: true



#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: tvpatrondev201703!
#    url: jdbc:mariadb://20.196.231.121:3306/kt_streaming?characterEncoding=UTF-8
#    hikari:
#      max-lifetime: 30000
#      connection-timeout: 33000

